### ISSUE TITLE
Program crashed with signal 11

### ISSUE THREAD

**Issue by Grabli66** [godot-nim/gdext-nim#136]
C:\WorkspaceTest\demo>nim c kaleidoscope/nim/bootstrap.nim
Hint: used config file 'C:\Users\grabl\.choosenim\toolchains\nim-2.2.0\config\nim.cfg' [Conf]
Hint: used config file 'C:\Users\grabl\.choosenim\toolchains\nim-2.2.0\config\config.nims' [Conf]
Hint: used config file 'C:\WorkspaceTest\demo\kaleidoscope\nim\config.nims' [Conf]
................................................................................................................................................................................................................................................
C:\WorkspaceTest\demo\kaleidoscope\nim\src\kaleidoscope_class.nim(55, 9) Hint: 'texRect' is declared but not used [XDeclaredButNotUsed]
C:\WorkspaceTest\demo\kaleidoscope\nim\src\kaleidoscope_class.nim(5, 22) Warning: imported and not used: 'gdimage' [UnusedImport]
Hint:  [Link]
Hint: mm: orc; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
113299 lines; 2.281s; 220.41MiB peakmem; proj: C:\WorkspaceTest\demo\kaleidoscope\nim\bootstrap.nim; out: C:\WorkspaceTest\demo\kaleidoscope\nim\lib\windows\debug\bootstrap.dll [SuccessX]

C:\WorkspaceTest\demo>godot --editor --path kaleidoscope

C:\WorkspaceTest\demo>Godot Engine v4.3.stable.official.77dcf97d8 - https://godotengine.org

================================================================
CrashHandlerException: Program crashed with signal 11
Engine version: Godot Engine v4.3.stable.official (77dcf97d82cbfe4e4615475fa52ca03da645dbd8)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] error(-1): no debug info in PE/COFF executable
[2] error(-1): no debug info in PE/COFF executable
[3] error(-1): no debug info in PE/COFF executable
[4] error(-1): no debug info in PE/COFF executable
[5] error(-1): no debug info in PE/COFF executable
[6] error(-1): no debug info in PE/COFF executable
-- END OF BACKTRACE --
================================================================

**Comment by panno8M** [comment]
Hi, thanks for your report.
Does the same problem occur with anything other than kaleidoscope (e.g. dodge_the_creeps_2d or quick_template)?

**Comment by Grabli66** [comment]
Yes. I tested on kaleidoscope, dodge_the_creeps_2d and quick_template.
Same result.

**Comment by panno8M** [comment]
Can you try a different OS/PC?
Or check your CPU, it seems that in [some cases][1] the CPU is the cause of this error code.

[1]: https://github.com/godotengine/godot/issues/93862

**Comment by panno8M** [comment]
Could you please add the following to `demo/***/nim/config.nims` and try to compile and run it again?

```nim
switch("define", "Dev.debugCallbacks")
switch("define", "Dev.debugEvents")
```

**Comment by panno8M** [comment]
Due to lack of information, it is difficult to identify the problem (SIGNAL 11 is a generic error), so it is considered difficult to correct and I close it.

**Comment by Mashmashin** [comment]
Hi, I have just started to work with gdext-nim so I might be missing some critical/fundamental information on how to pull things off property but I have been encountering the same signal 11 crash when trying to print a custom Class's property that also extends a Node.

My project has the CustomClass like this:

```nim
type CustomClass* {.gdsync.} =
  ptr object of Node
    node_test* {.gdexport.}: Node
```

Then in Godot I have the following scene structure:
``` 
┖╴CustomClass
    ┖╴Node
```

And finally, the NodeTest has:
```gdscript
extends CustomClass

func _ready() -> void:
	print(node_test) #causes signal 11 when it is not null
	#print(node_test.name) #works as intended
	#print(get_node_test()) #works as intended
 
```

If Custom class's node_test property is not set the game runs normally but the moment I assign a Node to it it causes the signal 11 crash. This is weird to me since the Node is actually there, if I print any of it's property like it's name it prints normally. Also, if I call this via get_node_test() it works perfectly normal as well. The same thing happens with resources as well. Am I missing something here? 

[11.txt](https://github.com/user-attachments/files/20622682/11.txt)

**Comment by panno8M** [comment]
@Mashmashin 
Hello. Thank you for the additional report. I appreciate your detailed explanation. Please tell me two more things.
 
1. What OS are you using?
2. Add the following two lines to the end of config.nims, build and run again, and tell me the standard output. 
   ```nim
   --define: "Dev.debugCallbacks"
   --define: "Dev.debugEvents"
   ```

**Comment by Mashmashin** [comment]
Sorry it took so long!

I'm using the following:
```
OS Name: Microsoft Windows 11 Home
OS Version: 10.0.26100 N/A Build 26100
System Type: x64-based PC
Engine version: Godot Engine v4.4.1.stable.official (49a5bc7b616bd04689a2c89e89bda41f50241464)
```

Here are the stuff that got printed in VSC when I ran build-all and run with debug/callbacks:
[build-all.txt](https://github.com/user-attachments/files/20623076/build-all.txt)
[run.txt](https://github.com/user-attachments/files/20623077/run.txt)

However, when I try to open the project it just closes. I tried running these separately, the debugEvents one seemed to be pretty much the same as the run log I provided but the debugCallbacks one seems a bit different: 

[callbacks.txt](https://github.com/user-attachments/files/20623348/callbacks.txt)

The project still crashes though. The moment I take both of those debug configurations off it continues working normally. :d

EDIT: This signal 11 seems to actually haunt me in a completely fresh project that has those configs enabled?

**Comment by panno8M** [comment]
The gdext-nim using a legacy instantiation mechanism, so backward compatibility may have been lost.

It will likely take several days to resolve.

**Comment by panno8M** [comment]
@Mashmashin 
I have fixed what appears to be the cause. Could you please try reinstalling gdext using the following method to see if the problem is resolved?

```bash
nimble uninstall gdext
nimble install https://github.com/godot-nim/gdext-nim@#devel
```

**Comment by Mashmashin** [comment]
Yes it does not crash anymore, thank you so much! This might be a bit offtopic now but is it normal that a custom Node prints blank by default? Do I need to provide my own to_string() or something?

**Comment by panno8M** [comment]
> is it normal that a custom Node prints blank by default? Do I need to provide my own to_string() or something?

That's a bug. I will fix it so that Godot's to_string is used by default.

It should be done within a few hours, but if you can't wait, you can work around it by overriding `toString` as follows.

```nim
method toString*(self: MyNode; r_is_valid: ptr Bool; p_out: StringPtr) =
  cast[ptr String](p_out)[] = self.name + gdstring(":<" & $typeof(self) & "#" & $self.getInstanceID & ">")
```

**Comment by panno8M** [comment]
@Mashmashin 
I fixed the two bugs you pointed out and reflected them in the main branch.

* [x] Crash with signal 11 on Windows
* [x] Fails to stringify custom nodes

```nim
nimble uninstall gdext
nimble install gdext
```

Thanks again for your help.

**Comment by Mashmashin** [comment]
Uh oh not sure why but the 0.12.01 is still crashing. I double checked and the https://github.com/godot-nim/gdext-nim@#devel one does not crash.

**Comment by panno8M** [comment]
hmm, that's strange...

Did you reinstall gdext@#devel and try it again, or did you revert to the development version that was originally installed?

Can you create a reproducible example?

**Comment by Mashmashin** [comment]
I'll have another crack with this. I went through these steps: 
* Ran the following commands: 
```
nimble uninstall gdext
nimble install gdext
gdextwiz new-extension release
``` 
* Opened gdmyclass.nim and added the following to MyClass:
```nim
node_to_print* {.gdexport.}: Node
```
* ran build-all
* Opened project.godot
* Added MyClass to a scene
* Attached a script to MyClass with the following logic:
```gdscript
extends MyClass

func _ready() -> void:
	if Engine.is_editor_hint():
		return 
	print(node_to_print)
```
* Ran the scene, print results in <Object#null> as it should do
* Added a regular Node and assigned it as MyClass's note_to_print
* Ran the scene again, the console prints the [following](https://github.com/user-attachments/files/20641330/node_print.txt)
* Tested printing node_to_print.name, works as intended
* added ```--define: "Dev.debugCallbacks"``` to the config.nims and called ```gdextwiz run``` resulting in [this ](https://github.com/user-attachments/files/20641350/print_callbacks.txt)
* Clicked the project open, resulting in a crash
* ran ```godot --editor``` to print the logs, it's the exact same as above
*  replaced the callbacks define with ```--define: "Dev.debugEvents"``` and ran the project resulting in [this](https://github.com/user-attachments/files/20641355/print_events.txt)
* Tried opening the project once more via executable and this time the project does not even show up, earlier it stuck as if were loading something. When running godot --editor it prints the usual signal 11 logs.
* Added both --defines this time and ran the project, results seem to be the exact same as with just the Dev.debugEvents
```
nimble uninstall gdext
nimble install https://github.com/godot-nim/gdext-nim@#devel
``` 
* Called gdextwiz run on the same existing project
* Tested the project with both --defines together and separately. The results seem to be the exact same. 
* It looks like the node_to_print print might not even be a part of this problem as these crashes actually happened without it being set?
* Without either one the project launches and when printing node_to_print that is not null, it works as it works regularily.
* Added another MyClass as a child for the root MyClass and set the node_to_print to it. Print does not crash the project, but it is still blank.

I will repeat the first half of these steps with a fresh project and report if there are anything that differs from these results. Not sure if I am stating something totally obvious to you but it seems to me that the culprit might actually be those debug tools rather than the Node?

Actually yeah I tested a completely fresh project with the extra configs and it crashes.

**Comment by panno8M** [comment]
It appears that 0.12.1 has not been installed correctly. Please run the following command and look for the gdext entry:

```bash
nimble list -i --ver
```

You can install 0.12.1 reliably by doing the following

```bash
nimble install gdext@0.12.1
```

When I tried it, `nimble install gdext` installed 0.12.0. The cause is currently under investigation.

We will treat debugging tool malfunctions as separate issues.

**Comment by Mashmashin** [comment]
Oh man I feel dumb for not noticing that. The printing works now as intended. Thank you for your hard work!
